### ISSUE TITLE
Extremely high memory and CPU usage

### ISSUE THREAD

**Issue by nodingneu** [codota/TabNine#183] opened 2019-10-31 17:00 UTC
I use TabNine in vim.

When I start vim (with simply `vim`, empty editor), the TabNine process is created and consumes 1.37 GB of memory.

That seems insane already.

For every couple seconds spent "editing" (typing random english sentences that pop into my head into the file), the memory usage increases by 0.05 GB.

Also the CPU usage is consistently >600% while editing.

Here's a video of me spewing stream of consciousness:

https://youtu.be/FgMe6ejqkhQ

Whirring fans is annoying. I have only used tabnine for less than a day so am not completely familiar with its problems, but these couple things were glaringly obvious to me once my computer became generally unresponsive by simply leaving a couple vim sessions open in the background.

**Comment by Alpha-Monocerotis** [comment] 2019-11-03 07:47
It seems reasonable as the local model is larger than 600MB, running such a model in a local environment that requires 1.37GB memory seems not very weird.

**Comment by ammkrn** [comment] 2019-11-03 18:49
I'm also getting >800% CPU spikes on a 12 core machine and ~1.6Gb memory use in VSCode :

Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-16T10:22:16.623Z
Electron: 4.2.11
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.14.149-1-MANJARO

**Comment by Shougo** [comment] 2019-11-03 22:47
You can disable Tabnine local feature by `Tabnine::config`.

**Comment by theonlygusti** [comment] 2019-11-04 06:34
Disabling TabNine local just stops TabNine from working at all, it's forever `Establishing connection to TabNine Cloud...`

**Comment by skorokithakis** [comment] 2019-11-12 17:43
I am also affected by this. At times my entire computer freezes.

**Comment by thomashzhang** [comment] 2019-11-19 23:11
I also want to jump in. I absolutely love this plugin. It's amazing! But it does take up a lot of memory and it sometimes makes VSCode feels slow even on my 16GB memory machine. I know it's not easy to just waive a hand and say "well, let's just get something that uses less memory" but it definitely is an issue. In the meantime, I'll still be using this plugin, but would love an option to use less memory even at an accuracy cost (again easier said than done).

Thank you!

<img width="704" alt="vscode" src="https://user-images.githubusercontent.com/2775684/69194639-7595f200-0ade-11ea-9e90-bc067e3f4a14.PNG">
<img width="630" alt="tabnine" src="https://user-images.githubusercontent.com/2775684/69194641-7595f200-0ade-11ea-9546-e9a3b8955add.PNG">

**Comment by kmate95** [comment] 2019-12-12 22:01
The first out of memory crash on my new PC with 64 GB RAM.  

![mmc_toqMXlW8QO](https://user-images.githubusercontent.com/6104679/70752581-394b5f80-1d33-11ea-8f9c-f2505d438d7f.png)

**Comment by project-delphi** [comment] 2020-01-29 02:19
Suffering the same - is a shame, since otherwise is a great tool.

**Comment by haiodo** [comment] 2020-02-14 06:34
Same for me, but even worse.
<img width="868" alt="Screenshot 2020-02-12 at 18 00 47" src="https://user-images.githubusercontent.com/477235/74507346-b7440680-4f2e-11ea-9be1-3060c3d344ef.png">

**Comment by drorweiss** [comment] 2020-02-16 05:34
Hi All, we have a fix in beta (version 2.3.4) for excessive CPU and memory consumption by TabNine.
We'd appreciate it if you try it out and let us know if it solves the issue for you.
To try the fix, you have to enable the beta version. Just open TabNine's config by typing TabNine::config in your editor, and then check both **Update TabNine automatically** and **Receive beta releases of TabNine** Then, restart your editor, and press TabNine::confiig to verify you have TabNine 2.3.4. or newer.  Please let us know if this version solves the problem for you. We plan to make it available to all users in a couple of weeks.

**Comment by kivervinicius** [comment] 2020-03-09 12:51
@drorweiss how i update this in vscode?

**Comment by drorweiss** [comment] 2020-03-09 12:55
It is now released to all users and should update automatically.
Type TabNine::version to see your version number - It should be 2.3.7 or later. See screenshot:
![image](https://user-images.githubusercontent.com/1917767/76214607-c9575300-6215-11ea-9658-9e71d92d3e85.png)

**Comment by kivervinicius** [comment] 2020-03-09 12:57
@drorweiss ok, thanks, on my computer still uses 2.5 g

**Comment by amircodota** [comment] 2020-03-16 13:09
Hi, everyone who wrote on this issue.

We have since released a version that should improve TabNine's cpu and memory consumption.
Would really appreciate your help in trying it out and seeing if the situation improved.

Thanks a lot!

**Comment by Xunjin** [comment] 2020-03-29 14:30
As you can see my version:

![image](https://user-images.githubusercontent.com/31026338/77851278-a1249980-71ae-11ea-9a95-c0242574775a.png)

Memory consumption:

![image](https://user-images.githubusercontent.com/31026338/77851372-3cb60a00-71af-11ea-8065-a4adc0b263d2.png)

Environment: Ubuntu 19.10
Vscode:
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-42-generic

**Comment by shuxiao9058** [comment] 2020-03-29 17:20
perhaps the modes of TabNine should provided two version，large for huge memory machine， and smaller for lower machine. or optimize the mode to make it smaller.

**Comment by amircodota** [comment] 2020-03-29 18:54
@Xunjin and @shuxiao9058 Thank you for your feedback.

Memory footprint of 1.7GB is not uncommon when TabNine local is enabled.
In fact, it can grow up to 2.5GB (depending on project size), but it should not grow much beyond that. Before it could grow without bounds, as one of the reports above shows ~124GB (!!) RAM.

If you do not wish to use that much RAM, you can disable deep TabNine local, which is responsible for most of the memory usage.
If you still wish to receive deep suggestions, you can choose to use TabNine cloud (a paid option).

**Comment by Xunjin** [comment] 2020-03-30 16:20
@amircodota No problem, just saw that you tagged a help wanted, so came for help (I guess).

IMHO the tools seems way better than before, In the past had some huge CPU spikes which doesn't happen quite often.

@shuxiao9058 pointed in other issues that could be other optimizations, it's not everybody who has powerful machines or/and have available 2.5 GB just for TabNine... Maybe it's worth looking for it ?!

Well, that's my 2 cents :)

**Comment by amircodota** [comment] 2020-03-30 18:28
@Xunjin Thanks for the feedback.

We are definitely looking into ways of reducing the memory footprint. Stay tuned...

**Comment by easonlau02** [comment] 2020-04-11 06:25
Got this issue, after upgraded to the latest MacOS `10.15.4`.
Only open one VS code window and one project. It will get high MEM while typing several code lines. Hope it will be fixed.

![image](https://user-images.githubusercontent.com/3955431/79037010-389ed900-7c00-11ea-8985-46babbac12c1.png)

![image](https://user-images.githubusercontent.com/3955431/79036983-02f9f000-7c00-11ea-8bbd-a2895b6b33be.png)

**Comment by easonlau02** [comment] 2020-04-16 06:25
@amircodota if any solution for it, my highly configured Mac is running with high MEM.

**Comment by amircodota** [comment] 2020-04-16 10:44
Hi @easonlau02 

See [above comment](https://github.com/codota/TabNine/issues/183#issuecomment-605682651)

**Comment by HenrijsS** [comment] 2020-04-24 12:13
This is still an issue.
I have node_modules listen in .gitignore but it still chonks up my CPU and RAM like crazy.
This doesn't occur when I'm working with non-npm/node projects.

**Comment by amircodota** [comment] 2020-04-24 18:23
@HenrijsS 

A few questions:

1. What editor are you using?
2. Do you have tabnine local enabled? If so, can you disable and see if it still reproduces?
3. Is your project open source by any chance? Would love to get the code and try to reproduce

**Comment by HenrijsS** [comment] 2020-04-24 20:30
> @HenrijsS
> 
> A few questions:
> 
> 1. What editor are you using?
> 2. Do you have tabnine local enabled? If so, can you disable and see if it still reproduces?
> 3. Is your project open source by any chance? Would love to get the code and try to reproduce

1. Visual Studio Code
2. I only use TabNine local because I'm currently a free user.
3. Unfortunately no, it is a private project for a client.

**Comment by amircodota** [comment] 2020-04-26 08:42
@HenrijsS would it be possible for us to get the package.json file only, along with relevant lock files (yarn.lock or package-lock.json), so that we can create a similar project?

**Comment by Elyx0** [comment] 2020-07-12 17:48
How do I disable it per project? I only need auto complete on my "main" the other VScode instances are just to browse code. That would fix the insane memory hogging for me

**Comment by dominicboston** [comment] 2020-07-14 22:38
Is there any progress on reducing RAM usage for TabNine? I'm on 2.8.1 and it normally used between 1.2gb and 1.5gb. Using Atom

Thanks Dom

**Comment by DevCentre** [comment] 2020-08-03 14:19
I really enjoyed the tabnine concept, but as well pointed here, it is a huge memory hog. I have 16gb of ram, but as a developer we keep so many things opened which has a huge impact. I've disabled it for not (haven't uninstalled) hopping this issue could be addressed.

**Comment by timnolte** [comment] 2020-09-28 19:18
After thinking my problem was too many Google Chrome windows/tabs open I started looking into my Neovim/Vim as the culprit because my machine ends up becoming unresponsive when editing code. I'm thinking this is hitting me pretty hard and I'm finding it pretty much a killer for my productivity, outweighing the benefits. Seems like there should be a way to restrict the amount of CPU it can use.

**Comment by hyliancoder** [comment] 2020-11-04 17:34
> How do I disable it per project? I only need auto complete on my "main" the other VScode instances are just to browse code. That would fix the insane memory hogging for me

https://github.com/microsoft/vscode/issues/15611#issuecomment-346179926

**Comment by Kshatriyaprithviraj** [comment] 2021-04-11 15:57
I'm still getting the same cpu and memory issues with Tabnine v3.2.17

```
Version: 1.56.0-insider
Commit: 845efe5d8e31079cc858131c95c36103d9439e74
Date: 2021-04-09T09:50:18.334Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 4.19.0-16-amd64
```

**Comment by peterjacobson** [comment] 2021-05-06 22:05
✨Love where this project is going, and sometimes it's super useful.

🍏 On m1 apple silicon macbook air, it's often the highest memory user, consistently at >1GB (~1.1GB) RAM, even when I put on "power saving" mode and turn off both local and cloud deep completions.

💸 Considering cancelling my subscription unless the RAM usage can come down. 

🙏Thanks to everyone working on this, I guess it's pretty complex!

**Comment by Kshatriyaprithviraj** [comment] 2021-05-15 20:15
> ✨Love where this project is going, and sometimes it's super useful.
> 
> 🍏 On
> 
> * m1 apple silicon macbook air,
> * vscode
> * plugin version 3.4.4
> * engine version 3.4.2-40
> 
> it's often the highest memory user, consistently at >1GB (~1.1GB) RAM, even when I put on "power saving" mode and turn off both local and cloud deep completions.
> 
> 💸 Considering cancelling my subscription unless the RAM usage can come down.
> 
> 🙏Thanks to everyone working on this, I guess it's pretty complex!

Though there's an alternative to **TabNine** i.e., Kite but that ain't as good as **TabNine** and it hurts that such a great helping-hand extension/service is eating loads of RAM. Not just consuming lots of memory but, it's parallelly causing heating issues.

**Comment by Onyoursix** [comment] 2021-09-21 23:12
TabNine works great and I love it. I am however experiencing high CPU usage when I use TabNine when I open an ipynb file (jupyter notebook) in VSCode. I switched from JupyterLabs to VSCode specifically for this extension. The extension uses about 10% of my CPU usage when I have a notebook open.

I run Ubuntu 21.04
Plugin Version: 3.4.27
Engine Version: 3.6.8-40

Keep up the good work!

**Comment by arsu-leo** [comment] 2022-02-04 11:22
Ended up to 6GB.

I restarted VS code and VS code update ran, so the VS code version will not match with the given here, but had to stop 2 times TabNine.exe process due taking all the ram memory.

Visual Studio Code
Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z (1 day ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

IDE: vscode
Plugin Version: 3.5.18
Engine Version: 4.0.60-41

**Closed** 2022-10-11 10:42 UTC
Labels: Type: bug, help wanted, wontfix

**Comment by Riccardo-Basile** [comment] 2023-12-13 14:59
I have to re-open this discussion:
lately, I was using TabNine locally, on a i9 9900K 8 core (16 threads) machine, with SSD and 32Gb of RAM and after only one hour of doing very simple coding the TibeNine process was eating something like 12Gb of RAM. Plus all the rest of the system ad apps.
I tried to close and re-open the editor but TibeNine is a separate thread and it was still there, going even bigger.
I judge this as unusable: it slowed down not only my editor but the machine itself too.
Unusable.
Deactivated but not uninstalled because I'd like to understand if there is a way to solve this problem.
If the only solution is using the cloud version, I'm not sure TibeNine will stay in my installation, because I can't and I don't want to depend on an internet (and it has to be a very good one!)
Hope to see something better, thank you any way for the efforts.

**Comment by netsentinel** [comment] 2024-05-17 13:22
closed👍
<img width="564" alt="Screenshot_43" src="https://github.com/codota/TabNine/assets/57228093/ef5586c4-3180-4313-86ef-7b7c4921f110">
