### ISSUE TITLE
TabNine is unable to install Go Language Server

### ISSUE THREAD

**Issue by jstrzebonski** [codota/TabNine#263] opened 2020-05-23 21:53 UTC
- OS version: Linux (Ubuntu 20.04 LTS)
 - Editor: vscode	
 - Editor version: 1.45.1	
 - Programming language: Go	
 - TabNine extension version: 2.8.1

**Issue Details:**
Go Language Server cannot be installed. TabNine gives me this error:
```
TabNine was unable to install the go semantic completion backend.
The command that failed was: `go get -u golang.org/x/tools/cmd/gopls`
For help, see tabnine.com/semantic.
Or, type TabNine::no_sem to disable semantic completion for Go.
(TabNine works well even without semantic completion.)

```

TabNine tries to install language server with command `go get -u golang.org/x/tools/cmd/gopls`, but if you check current documentation, it says that the only correct way to do it is this:
`go get golang.org/x/tools/gopls@latest`

Here's the link to doc -> https://github.com/golang/tools/blob/master/gopls/doc/user.md#installation

**Comment by Shougo** [comment] 2020-05-24 04:55
https://github.com/codota/TabNine/pull/212

The problem is already fixed in the latest version of TabNine.
Please use the latest version.

**Comment by Shougo** [comment] 2020-05-24 05:00
You may use the old version of config.
Please check your `~/.config/TabNine/TabNine.toml`.

**Comment by jstrzebonski** [comment] 2020-05-24 06:43
To install TabNine I used `ext install TabNine.tabnine-vscode` as documentation states (https://www.tabnine.com/install/). `TabNine::version` gives me `2.8.1` although in extension window it says `2.8.2`. If that is not the newest version, how can I obtain newer one?

In config directory I've got only `TabNineExample.toml`, should I rename it to `TabNine.toml`?
Also, in that toml file, there is still old installation command for Go Language Server:
```
[language.go]
command = "gopls"
args = ["serve"]
install = [["go", "get", "-u", "golang.org/x/tools/cmd/gopls"]]
```

**Comment by jstrzebonski** [comment] 2020-05-24 06:52
I renamed `TabNineExample.tomp` to `TabNine.toml` and tried to change `install` firstly to

```install = [["go", "get", "golang.org/x/tools/gopls@latest"]]```

and then to

```install = [["GO111MODULE=on", "go", "get", "golang.org/x/tools/gopls@latest"]]```

but without luck.

**Comment by jstrzebonski** [comment] 2020-05-24 06:58
OK, I apologize - I just saw the change introduced in #212 

```install = [["go", "get", "-u", "golang.org/x/tools/gopls"]]```

It works. Thanks.
Although now there's another error

```
TabNine was unable to start the go semantic completion backend.
The command tried was: `gopls serve`
This means you need to install the backend manually.
```

But I guess that's something for another ticket.

@Shougo thanks for help!

**Comment by Shougo** [comment] 2020-05-24 07:55
OK.

You should run the command manually to check.

**Comment by Eransho** [comment] 2020-05-25 07:11
> OK, I apologize - I just saw the change introduced in #212
> 
> `install = [["go", "get", "-u", "golang.org/x/tools/gopls"]]`
> 
> It works. Thanks.
> Although now there's another error
> 
> ```
> TabNine was unable to start the go semantic completion backend.
> The command tried was: `gopls serve`
> This means you need to install the backend manually.
> ```
> 
> But I guess that's something for another ticket.
> 
> @Shougo thanks for help!

Hi,
Glad to hear the initial issue is behind you.
As @Shougo suggested, plz try running the command manually and see it works for you.
If it doesn't plz open a separate issue and we will continue from there

**Closed by Eransho** 2020-05-25 07:11 UTC
