### ISSUE TITLE
Tabinine AI learns about Copy and Paste

### ISSUE THREAD

**Issue by MemeMan69421** [codota/TabNine#474] opened 2021-11-09 01:08 UTC
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]
    MacOS Big Sur
 - Editor: [e.g. vscode, intelij, sublime]
    VS Code
 - Editor version:
    1.62.0
 - Programming language: [e.g. js, ts, c++]
   c#
 - TabNine extension version:
    3.4.34
 - Engine version (could be located within Tabnine Hub): 
    3.7.25-42
**Issue Details:**
Tabnine decided to freak while I was writing to instead of showing ONE completion word(s). (screenshot explains this quite well
<img width="593" alt="Screen Shot 2021-11-08 at 20 01 06" src="https://user-images.githubusercontent.com/86630392/140843031-ee84107e-2bb0-4ff0-a083-a3e543f778c5.png">
)

gz#8485

**Comment by yonip23** [comment] 2021-11-11 09:00
Hey @MemeMan69421 
We're sorry for the poor experience, we'll add this to our backlog and will handle it asap.
Are you working on a single file by any chance? or a very small project? This will help us better understand the cause of this bug.

Thanks,
Yoni

**Comment by MemeMan69421** [comment] 2021-11-14 01:58
It's alright, don't worry about it.
In terms, of size, yes, I was working on a singular file that referenced other file variables, but the project is fairly large.
after I reported this issue, I didn't see anything like it again.
A good way to solve this issue would be to check if the AI suggestion falls under any specific category such as, repeating, duplicated suggestions, etc.

**Comment by yonip23** [comment] 2021-11-16 11:26
@MemeMan69421 We know this problem exists in some niche cases and are constantly working on improving our engine, so thank you for taking your time talking to us, and we'll take your case into consideration!

Im closing this issue as it seem to not reproduce, feel free to re-open/open a new one any time.
Kind regards,
Yoni

**Closed by yonip23** 2021-11-16 11:26 UTC
