### ISSUE TITLE
Use flow from node_modules

### ISSUE THREAD

**Issue by max-mykhailenko** [codota/TabNine#134] opened 2019-08-21 12:32 UTC
Will be great if you add support for local installed flow package, because each project has own supported flow version.

**Comment by dimacodota** [comment] 2020-05-07 19:44
Duplicate of #https://github.com/codota/tabnine-vscode/issues/68

**Comment by dimacodota** [comment] 2020-05-07 19:49
hey @max-mykhailenko  - you can use your project flow version by following these steps:

 - open Tabnine::config (command pallet -> tabnine: config)
 - locate your configuration folder ("Configuration path" in the first section)
 - navigate to your configuration folder (the path without the json file)
 - create a TabNine.toml file in this directory with following configuration(adjust the path relative to your project file and keep the ${project_root} placeholder)
```
[language.javascript]
command = "${project_root}/path-to-your-local-flow-version" 
args = ["--stdio"]
```
 
You can read more about how to configure it [here](https://www.tabnine.com/semantic)

**Closed** 2022-10-10 17:43 UTC
Labels: wontfix
