### ISSUE TITLE
compatibility issue on gitpods

### ISSUE THREAD

**Issue by gengjiawen** [codota/TabNine#324] opened 2021-01-18 08:11 UTC
**please complete the following information:**	
Gitpods is popular cloud IDE based on theia. `Tabnine works good generally`.
But I can't config it.

Sample project: https://github.com/gengjiawen/monkey-rust

![image](https://user-images.githubusercontent.com/3759816/104888405-abb35800-59a7-11eb-875f-ee1c1c594984.png)
![image](https://user-images.githubusercontent.com/3759816/104888478-c1288200-59a7-11eb-8d40-d191dae84f23.png)

**Issue Details:**

**Comment by boaz-codota** [comment] 2021-01-18 08:14
Thank you for letting us know @gengjiawen, we will look into that ASAP.

**Comment by boaz-codota** [comment] 2021-01-20 15:01
Couldn't easily reproduce, due to the fact that I could not install Tabnine on hosted gitpods. I'm not sure how you've done it.

The problem probably is something regarding communication, as Tabnine starts an http server (that might be killed by gitpods?) and that message you are seeing is being shown once communication with that server is lost.

Closing for now, sorry I couldn't figure it out.

**Closed by boaz-codota** 2021-01-20 15:01 UTC

**Comment by gengjiawen** [comment] 2021-01-21 00:26
> Couldn't easily reproduce, due to the fact that I could not install Tabnine on hosted gitpods. I'm not sure how you've done it.

Install directly from market. Or you can upload your own extension.
![image](https://user-images.githubusercontent.com/3759816/105257185-35d70880-5bc2-11eb-8181-e7b7714167cb.png)

> as Tabnine starts an http server (that might be killed by gitpods?) 

Not likely, since I start http server on gitpods all the time.
