### ISSUE TITLE
taking too much ram in cloud mood

### ISSUE THREAD

**Issue by zzobaer09** [codota/TabNine#571] opened 2022-11-30 06:43 UTC
while using cloud mood. tabnine takes almost 1.2 gb ram. it slow my computer and vscode.

gz#19691

**Comment by amirbilu** [comment] 2022-12-08 15:29
Request #19949 "tabnine is killing my pc :)" was closed and merged into this request. Last comment in request #19949:

Please fix this issue before i die. :)

some time age it took more then 2gb ram :0









 ![image.png](https://support.tabnine.com/attachments/token/JLnyYSLRWNyyPcn8S8bBJDb7T/?name=image.png) ![image.png](https://support.tabnine.com/attachments/token/dMti7JCZeAy1anggGrCcwFOGu/?name=image.png)<br><a href='https://tabninedesk.zendesk.com/attachments/token/KFr2Veg2Zs9rbLCcvy2zgvhx1' target='zd_attach'>image.png</a><br><a href='https://tabninedesk.zendesk.com/attachments/token/UofGLD2OJT77KUS0IQT5LJY9z' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by yonip23** [comment] 2022-12-08 16:11
@zzobaer09 Sorry for the late response
This situation is not uncommon - Tabnine indexes your current project locally, so this index can grow with time.
Are you working on a significantly large project?
Or, maybe you're working on single files, not inside a project at all?

Also, can you please share you config file content here? Its path is in the Hub -> Support -> General Info -> Config file path

Kind regards

**Comment by zzobaer09** [comment] 2022-12-08 16:35
i am working in a Django and React Project
this tabnine just killing my computer.

my config file is attached below

**Comment by yonip23** [comment] 2022-12-10 22:10
@zzobaer09 where is your config file? You said you have attached it, but I can't seem to find it 😀

**Comment by zzobaer09** [comment] 2022-12-11 12:02
idk why you it is not showing you. but i can see. im giving you the code
here.


//config file code.

{
  "version": "4.0.60",
  "hide_promotional_message": false,
  "beta_enabled": "Yes",
  "ignore_all_lsp": false,
  "creation_time": "2022-01-26T18:24:26.845578700Z",
  "guuid": "1e7dd92152fa15a50933924a1a815f97e3f9825ccfa1efe2e673991e583e0aa1",
  "semantic_status": {},
  "enable_telemetry": true,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers":
true,
  "deep_completions_work_mode": "CloudOnly",
  "hosted_deep_completions_enabled": "Enabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": 5,
  "line_suggestions": true,
  "omit_prefix_suggestions": false,
  "api_key": null,
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 48,
  "local_model_size": "Small",
  "model_hash_override": null,
  "local_indexing": false,
  "heartbeat_interval_seconds": null,
  "last_service_level": "FreeCloudRegistered",
  "override_beams": null,
  "override_context_length": null,
  "onboarding": {
    "model_type": null,
    "skipped_login": false,
    "completed": false
  },
  "has_git_repos": true,
  "gusr": {
    "dgc": "1e7dd92152fa15a50933924a1a815f97e3f9825ccfa1efe2e673991e583e0aa1"
  },
  "exclude_file_masks": null,
  "inline_suggestions_mode": true,
  "use_specialized_model_if_available": false,
  "empty_line_suggestions": false,
  "snippets_enabled_v2": true,
  "inline_suggestions_mode_clients": null,
  "tabnine_hub_port": null,
  "manually_selected_model": null,
  "hybrid_rendering_mode": null
}

**Comment by yonip23** [comment] 2022-12-13 23:11
@zzobaer09 Thank you for your cooperation

Can you say how many files are in your project? Is it especially large?
Do you have a `.gitignore` file in your root folder? If not, can you add a `.tabnineignore` file to your root folder and restart your IDE?
One last thing - Can you please try and work in a very small folder and let me know if this reproduces?
```
mkdir test
cd test
touch .tabnineignore
touch test.py
```

Sincere regards

**Comment by zzobaer09** [comment] 2022-12-14 14:38
i was working in a django and react project.
i tried working with a single file with .tabnineignore file but i end up
with this result
[image: image.png]

**Comment by yonip23** [comment] 2022-12-14 15:15
@zzobaer09 I'm sorry, but I can only see the text "[image: image.png]" - can you attach it here please?
I understand that you're working on a django and react project, but I'm asking for the size of your project (in files / disk size) 🙂 
I'm asking because Tabnine indexes your local files, so it can be the case that the ~2gb of ran that the process is taking is because of the indexing.
Kind regards

**Comment by zzobaer09** [comment] 2022-12-14 16:54
ok i have attached the image.this image is the result of a single python
file with .tibnineignore in root.
i dont think i want to give 825.8 Mb when im working in a single file. i
already used microsoft intelliCode but after this tabnine issue. it is
working fine.

my folder size is 375 MB and 40.5 k files and 5.6k folders in total.

![image](https://user-images.githubusercontent.com/78909101/207658145-e785e4f8-9ea9-49df-8600-163075d818b5.png)

**Comment by yonip23** [comment] 2022-12-15 14:21
Hi @zzobaer09 
1. You wrote ".tibnineignore" and this is a typo - should be `.tabnineignore`. Can you make sure that the file is named correctly?
2. I see that in your config file you have `"local_indexing": false` - When did you change it? Did you restart your IDE since you changed it? It should turn off indexing completely, so it's unclear to me how the single python file process takes less than the other one.
3. Do you have a `.gitignore` file in your python + react project?
Kind regards

**Comment by zzobaer09** [comment] 2022-12-15 15:47
1.my bad here but it was ".tabnineignore".

2.when i reported this issue then i get a mail and he said me to add `"local_indexing": false` . but it did not solved.
3. almost in every project i use .gitignore

**Comment by yonip23** [comment] 2022-12-18 08:33
Hi @zzobaer09 
Since we've eliminated the indexing issue, I suspect we'll need to further investigate on our side.
I brought it up to my team and will keep you posted on any updates.

I'm very sorry for the inconvenience, and thank you for reporting this.

Kind regards

**Comment by zzobaer09** [comment] 2022-12-19 11:46
Thank you for your response.

**Comment by amirbilu** [comment] 2023-01-04 13:09
@zzobaer09 I'm closing this for now, as it seems your issue was resolved. Feel free to reopen should you have any further questions.

**Closed by amirbilu** 2023-01-04 13:09 UTC
